[build]
  publish = "public"
  command = "yarn build"
[build.environment]
  YARN_VERSION = "1.3.2"
  YARN_FLAGS = "--no-ignore-optional"
[[redirects]]
  from = "agitated-lumiere-fa5ea8.netlify.com"
  to = "https://distributed.sh"
  status = 200
  force = true
[[redirects]]
  from = "http://distributed.sh"
  to = "https://distributed.sh"
  status = 200
  force = true
